server:
  port: 8080
spring:
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus, loggers, beans, env
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  info:
    git:
      mode: full
    build:
      enabled: true

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc.pool: DEBUG
